import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from "next/font/google";
import { Inter } from "next/font/google";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Lalinda Dias - Personal Portfolio</title>
        {/* This script adds support for scroll-driven animations in all browsers */}
        <Script
          src="https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${playfair.variable} ${inter.variable} font-Inter`}>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-3KRX0CFPJ5"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-3KRX0CFPJ5');
          `}
        </Script>

        {children}
      </body>
    </html>
  );
}
